blank_issues_enabled: false
contact_links:
  - name: ⚠️ Anime extension/source issue
    url: https://github.com/jmir1/aniyomi-extensions/issues/new/choose
    about: Issues and requests for extensions and sources should be opened in the aniyomi-extensions repository instead
  - name: 📦 Aniyomi extensions
    url: https://aniyomi.org/extensions
    about: Anime extensions and sources
  - name: 🧑‍💻 Aniyomi help discord
    url: https://discord.gg/F32UjdJZrR
    about: Common questions are answered here
